language: java 
jdk:
  - openjdk7
  # maintainers to fix their pypy-dev package.
# command to install dependencies
# command to run tests

mvn test


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
